"""change table

Revision ID: b980a9d375db
Revises: aa2f09dd2cb2
Create Date: 2021-11-30 08:51:31.430268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b980a9d375db'
down_revision = 'aa2f09dd2cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('calculation', sa.Column('lead_time', sa.Interval(), nullable=True))
    op.add_column('calculation', sa.Column('calculation_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation', 'calculation_name')
    op.drop_column('calculation', 'lead_time')
    op.drop_column('calculation', 'start_date')
    # ### end Alembic commands ###
